---
deployment:
  tasks:
    - export PUBLICPATH=/home/ybuqor/public_html
    - export DEPLOYPATH=/home/ybuqor/buq_node_app
    - /bin/cp -R work/cpanel-static/* $PUBLICPATH/ || true
    - /bin/cp -R app $DEPLOYPATH/ || true
    - /bin/cp -R public $DEPLOYPATH/ || true
    - /bin/cp -R db $DEPLOYPATH/ || true
    - /bin/cp package.json $DEPLOYPATH/ || true
    - /bin/touch $DEPLOYPATH/tmp/restart.txt || true
